server:
  port: 8080

spring:
  application:
    name: cosmere-api
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:sqlite:cosmeredb.db
    username: admin
    password: admin
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: com.cosmere.configuration.SQLiteDialect
    hibernate:
      ddl-auto: update
      
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka-server-0.eureka-server.default:8761/eureka,http://eureka-server-1.eureka-server.default:8761/eureka