apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pv.claim.name }}
spec:
  storageClassName: {{ .Values.pv.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pv.storage }}